name: Demo Python
on: [push]

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      # C'est CETTE étape qui récupère votre code
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Lancer le script
        run: python job.py