name: Intégration Continue (CI)
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code
      - uses: actions/checkout@v4
      
      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installer la librairie de test
      - name: Install dependencies
        run: pip install pytest

      # 4. Lancer les tests
      - name: Run tests
        run: pytest test_calculs.py

